#   ___ _                 ___ _
#  / __| |___ __ _ _ _   | _ (_)_ _  __ _
# | (__| / -_) _` | ' \  |  _/ | ' \/ _` |
# \___|_\___\__,_|_||_|  |_| |_|_||_\__, |
#                                   |___/

settings:
  dynamic_ping: true
  others_ping_enabled: true
  stats: true

dynamic:

  medium_ms: 120
  high_ms: 180

  low_ms_color: "&a"
  medium_ms_color: "&e"
  high_ms_color: "&c"

permissions:

  ping: cleanping.ping
  others_ping: cleanping.ping.others
  reload: cleanping.reload

messages:

  prefix: "&d&lPING &7»"

  usage: "%prefix% &7Use: &d/ping [player]"

  only_players: "%prefix% &7This command is only for &dplayers&7."

  no_permission: "%prefix% &7You do not have the &dpermission &7to do this."
  not_online: "%prefix% &7The user &d%user% &7is not &donline&7."

  ping: "%prefix% &7Your latency is: &d%ping% ms"
  others_ping: "%prefix% &d%user%&7's latency: %ping% ms"

  reloaded: "%prefix% &7Configuration reloaded &dsuccessfully&7."
